### ISSUE TITLE
Package includes empty index.d.ts

### ISSUE THREAD

**Issue by jaap3** [buttons/vue-github-button#12]
This is causing an issue in my Vue 3 / TypeScript project (the project won't build `error TS2306: File '/code/node_modules/vue-github-button/index.d.ts' is not a module.`).

I've worked around it by overriding the declaration, with the following content:

```typescript
declare const GithubButton: import("vue").DefineComponent<{
  href?: string
  ariaLabel?: string
  title?: string
  dataIcon?: string
  dataColorScheme?: string
  dataSize?: string
  dataShowCount?: string
  dataText?: string
}>
export default GithubButton
```

Would be nice if a proper `index.d.ts` was included.

**Comment by ntkme** [comment]
When I was testing it a long time ago, just by using `defineComponent` in JS allows vue's TS integration to infer the prop automatically so that an empty definition worked fine. I will take a look at what is needed now.

**Comment by ntkme** [comment]
v3.1.0 should fix the TS2306 error

**Comment by jaap3** [comment]
Thank you! I've upgraded and was able to drop my workaround without any issues.
