### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by mauriciabad** [buttons/vue-github-button#4]
When I try to use the component it gives me the error in [index.js line 3](https://github.com/ntkme/vue-github-button/blob/master/index.js#L3):

```
Uncaught TypeError: Cannot read property 'extend' of undefined
```

I think it may be because my project uses Vue 3 and the component is not compatible.

**Comment by ntkme** [comment]
Please try `vue-github-button@next` :

```
npm install vue-github-button@next
# OR
yarn add vue-github-button@next
```

Feel free to reopen this if you still face issue.

**Comment by mauriciabad** [comment]
Awesome job, you've updated it so fast! Thank you!
